name: Sync CD

on:
  push:
    branches:
      - main

jobs:
  build_push:
    runs-on: ubuntu-latest
    name: Build & Push
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: maxrsb/rsb-photo-sync:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2

      - name: Write kubeconfig to ~/.kube/config
        run: |
          mkdir ~/.kube
          echo '${{ secrets.KUBE_CONFIG }}' > ~/.kube/config

      - name: Terraform init and apply
        run: |
          cd infra
          terraform init
          terraform apply -auto-approve -var="image_tag=${{ github.sha }}"
